### ISSUE TITLE
Edit/delete bookmarks

### ISSUE THREAD

**Issue by dluciv** [skx/bookmarks.public#12]
It wil be useful to edit and delete bookmarks.

May be the most minimalistic way is to:

- Add small clickable item near bookmark that switches **Add** form to **Edit/Delete** mode
- When in **Edit/Delete** mode, the form should have **Done**, **Delete** and **Cancel** buttons instead of **Add** one

There is also a problem in dealing with duplicates. And even what exactly to consider diplicates.

Hope to see other suggestions here =)

**Comment by dluciv** [comment]
Please consider https://github.com/skx/bookmarks.public/pull/13 =)

**Comment by skx** [comment]
Took a bit of work since you didn't rebase your fork before the merge request.  In the future that would speed things up :)

I added a OK/Cancel prompt to the delete support because it is too easy to click by mistake.  But yeah good job, thanks.

**Comment by dluciv** [comment]
Yes, removing with confirmation looks much more reliable and comfortable, thank you.
