### ISSUE TITLE
Save feature disappeared

### ISSUE THREAD

**Issue by dluciv** [skx/bookmarks.public#14]
https://github.com/dluciv/bookmarks.public/blob/master/index.html contains:

    <p> </p>
    <fieldset>
        <legend><b>Save Data </b></legend>
        <form id="saveForm" name="newForm">
            <button type="button" onclick="saveDataFile()">Save...</button>
        </form>
    </fieldset>

While https://github.com/skx/bookmarks.public/blob/master/index.html does not.

Problem very likely happens in this merge: https://github.com/skx/bookmarks.public/commit/0a9897b18096b7102ff723b5cd262f0e63bf48dc#diff-eacf331f0ffc35d4b482f1d15a887d3bL69

Original pull request contained saving markup: https://github.com/skx/bookmarks.public/pull/13/files#diff-eacf331f0ffc35d4b482f1d15a887d3bL68

**Comment by skx** [comment]
Sorry the merge wasn't clean because you didn't resync, so I did a bit of manul fixup.

If you are able to submit a new merge request against master I'll apply shortly.  Otherwise I'll try to patch up manually later tonight.

**Comment by dluciv** [comment]
Can't remember exactly, very probably my fault =)

https://github.com/skx/bookmarks.public/pull/15
