### ISSUE TITLE
Include creation date on saved data

### ISSUE THREAD

**Issue by hamoid** [skx/bookmarks.public#17]
This way you could sort bookmarks by date, and find a bookmark you created last week (if you don't remember the name or the tags).

**Comment by skx** [comment]
It's an interesting idea, definitely.  But I'm not sure how it would work in practice.

Editing the `.data` file to add new bookmarks is pretty straight-forward at the moment - my real installation has ~600 bookmarks at the moment.  Adding a timestamp, as something `Date.parse` could understand would make things a little more complex, even if it was just a new attribute of the `li` or `a` tag.

Probably the best way would be a pre-commit hook to add it on changed-lines, but that gets hard to distribute (as hooks aren't cloned).

I'd be curious to see how you'd solve this problem?

(Obviously using the on-page editor makes it easier, but I suspect most users ignore that.  I know I do.)

**Comment by hamoid** [comment]
Awesome! :) I was planning to use the web interface anyway. If I was editing the file manually, I think json would be much more comfortable than pure html. Also we could add a command to our text editor to insert the current timestamp.
