### ISSUE TITLE
Feature Request: Integrated Git

### ISSUE THREAD

**Issue by Immortalin** [skx/bookmarks.public#18]
On mobile devices, accessing git repos and local html files is not always as simple as desktop. Having a integrated Git sync wouldbe really useful. This can be done via this [library](https://github.com/creationix/js-git).

**Comment by skx** [comment]
This is an easy "won't fix".

While it is assumed git is the storage mechanism, there is nothing in _this_ project that mandates it, or works with it particularly (beyond the fact that this repository is hosted on github).

For all I know other users will host their files on dropbox, or similar.

I accept that git is hard on mobile devices, but I'd suggest that they'd just be read-only in that case.

**Comment by GeorgBisseling** [comment]
My synchronized bookmarks came a long way from Opera to SeaMonkey to Firefox and now I see myself using Chrome/Chromium regularly. I really like the idea of having my bookmarks not stored on an alien  server. I like your very transparent approach that does not use PHP or a heavyweight SQL database behind the scenes like other solutions do. I mean who would use a database dump to (re)store his/her bookmarks?

I put some effort in the hierarchical organization of my bookmarks. Is there any chance to have that replicated?
