### ISSUE TITLE
Hierarchy

### ISSUE THREAD

**Issue by GeorgBisseling** [skx/bookmarks.public#25]
My synchronized bookmarks came a long way from Opera to SeaMonkey to Firefox and now I see myself using Chrome/Chromium regularly. I really like the idea of having my bookmarks not stored on an alien server. I like your very transparent approach that does not use PHP or a heavyweight SQL database behind the scenes like other solutions do. I mean who would use a database dump to (re)store his/her bookmarks?

I put some effort in the hierarchical organization of my bookmarks. Is there any chance to have that replicated?

**Comment by skx** [comment]
Thanks :)

I realize that many people do sort their bookmarks into a complex series of hierarchies, but I think that this would be beyond the scope of this project.  That said if you come up with a clean approach I'd love to see it.  Right now we store the bookmarks in a single list, so we have:

      <ul>
      <li><a href="http://example.com/">one</a></li>
      <li><a href="http://example.com/">two</a></li>
      ..
      </ul>

With that view in mind it is certainly possible we could show _nested_ bookmarks, at least one level like so:


      <ul>
      <li><a href="http://example.com/">one</a></li>
      <li><a href="http://example.com/">two</a>
        <ul>
         <li><a href="http://example.com/">one</a></li>
         <li><a href="http://example.com/">two</a></li>  
        </ul></li>
      ..
      </ul>

The hard part would be working out how to view that neatly, as we're suddenly then looking at a _tree_ not a list, albeit one with limitations.  I expect it would be possible to use some of the jQuery magic to make it expand/collapsible, but I also suspect the changes would be pretty invasive and hard to write in a way that would make all current users happy.

**Comment by GeorgBisseling** [comment]
It would be nice if there were a tree-like HTML-Element that would cause the browsers to offer expand and collapse, but afaik there is not. But it is remarkable that firefox uses nested definition list when exporting bookmarks to HTML. There are tons of tree widgets offered on top of jQuery. I understand that even deciding which one to use could cost hours and hours. But is there something simple already built into jQuery? I found an example in a book and shamelessly copied it here: [http://geek-georg.mooo.com/jq/Listings/Kapitel_05/Beispiel-08-Treemenu/Listing-5-18.html](url)
