### ISSUE TITLE
Sort bookmarks to minimize diff on changes

### ISSUE THREAD

**Issue by dluciv** [skx/bookmarks.public#28]
When showing different tags, bookmarks are reordered in the file.

When making changes and saving then, resulting diff actually contains some lines moved in the file without any use of this reordering.

I suggest adding one line to `saveDataFile()` function:

    ...
    // beautify text
    text = text.trim().replace(/[\n\r]+/g, "").replace(/<\/li><li/g, "</li>\n<li");
    text = text.split('\n').sort().join('\n');
    ...

Last line will actually minimize diff after changes.

If this feature is desired, I can create a pull request on it.

**Comment by skx** [comment]
> If this feature is desired, I can create a pull request on it.

Will result in massive-churn the first time, but the end result is probably worth it.

Please do create your pull request, and I'll merge immediately.

**Comment by dluciv** [comment]
Ok, thank you.
Right after finishing with previous pull request I will suggest this one!

**Comment by skx** [comment]
Great - should be easier for me to apply that one.  Obviously the first time they'll be sorted it'll be a big change, but after that it'll be incremental and simple.
