### ISSUE TITLE
save the bookmarks

### ISSUE THREAD

**Issue by gabreal** [skx/bookmarks.public#3]
hello,

i'm sorry, i actually don't want to open an issue but don't know how else i can ask about that bookmarks page ...

how can i actually save the bookmarks that i've added?

i tried the browser's /Save As/ without luck. Then I was working on implementing a button for saving but i didn't figure out how to do that properly. I added a button which inserts some anchor which has the document as data uri, but the formating gets entirely mixed up ...

how do you do this?

cheers,
gabriel

**Comment by skx** [comment]
I had to look at this myself to answer - but feel free to open issues to ask questions, I certainly don't object.

The functionality to add bookmarks as added via [this pull request](https://github.com/skx/bookmarks.public/pull/2) from [angelodag](https://github.com/angelodag).  If you read the code it really doesn't do much:

* there is a form for adding the new entry.
* When you submit it the function `addBookmark()` is called.
     * This clears the add-bookmark form.
     * And adds the children to the main display.

So there's nothign there about saving locally, or persistence.  In short it doesn't work the way that you'd expect it to - I guess I should remove it.

Me?  I open the file in Emacs add my new bookmarks, save, and then commit to the repository.  So I've never really looked at the add-bookmark from in detail before - the other changes submitted in that same pull-request were sufficiently good I didn't care too much about that specific feature.

**Comment by gabreal** [comment]
Uh,  I didn't check where that feature came from. Is it possible now to push that issue/question to @angelodag 's repo?

**Comment by skx** [comment]
I think you'd need to report it afresh there..

**Comment by angelodag** [comment]
No need, I am following. I explain you how it is supposed to work:

1. open the file in the browser
2. add the new bookmark (title, address and tags)
3. use the browser "save as" to save the modified page.

There is a big caveat, when you want to add a bookmark you do not have to di any other operation like filtering for tag or search. If you save while the pages shows filtered data (generate by the internal javascript) then the page will contain the filtered data.

There is another caveat, when you save the page, in the html you will get also the expanded reference to the page's current location, if you move it somewhere else then it will break unless you manually edit the page.

In general the html saved by the browser is rather ugly (long lines, lost alignment...) and this makes difficult to compare different versions of the file. For me , I use a "post-processing" script that keeps the alignment consistent across multiple save operations and removes the reference to the current location and file name (and some minor stuff, you can see it below):

```
#!/bin/bash
# 1 remove the expanded tags
# 2 break <a> on multiple lines
# 3 break <li> over multiple lines
# 4 remove empty lines
# 5 remove reference to file name and location
# 6 replace local reference to jquery with internet one
sed -i.bak -e 's/<a class="tagfilter".*<\/a>[,|.]//g' \
           -e 's/a>, <a/a>,\n <a/g' \
           -e 's/li><li/li>\n<li/g' \
           -e '/^\s*$/d' \
           -e 's/file:.*#/#/g' \
           -e 's/type="text\/javascript".*js"/type="text\/javascript" src="http:\/\/code\.jquery\.com\/jquery-2\.1\.1\.min\.js"/g' \
"$1"
```
 I did test it in IE, Firefox and Chrome, just to be sure I just re-tested just in Chrome

**Comment by gabreal** [comment]
Now I got it. I tried in Iceweasel/Firefox with Save As but Web Page, HTML only. This only gave me the original page. With Web Page, complete I get the file that you mention.

In fact I implemneted a button with this function:
```javascript
            function saveBookmarks() {
                var node = document.doctype;
                var html = "<!DOCTYPE "
                        + node.name
                        + (node.publicId ? ' PUBLIC "' + node.publicId + '"' : '')
                        + (!node.publicId && node.systemId ? ' SYSTEM' : '') 
                        + (node.systemId ? ' "' + node.systemId + '"' : '')
                        + '>'
                        + document.documentElement.outerHTML;
                var a = document.body.appendChild(
                        document.createElement("a")
                );
                a.download = "bookmarks.html";
                var encdoc = window.btoa(unescape(encodeURIComponent(html)));
                a.href = "data:text/html;charset=utf-8;base64," + encdoc;
                a.click(); 
                body.removeChild(a);
            }
```

but it results in the same scrambled code ... thank you anyway.

**Comment by dluciv** [comment]
I guess it will be very comfortable to add an ability to save data file. Very probably we can look at TiddlyWiki to discover how saving can be done.

**Comment by dluciv** [comment]
Please consider https://github.com/skx/bookmarks.public/pull/11
