### ISSUE TITLE
do not work in MacOS Safari

### ISSUE THREAD

**Issue by hudecof** [skx/bookmarks.public#36]
Hi,

could you get it working in Safari browser?

**Comment by skx** [comment]
If I received a bug-report with output from the javascript-console, or any similar integrated debugging tool, which pointed to a problem I'd be happy to try to fix it.  But I'd be stabbing in the dark making changes to resolve a problem I couldn't see.

So realistically if this fails on Safari/Mac it would need somebody else to investigate that, and contribute the appropriate fix(es) to me.

In short:

* If there is an explicit error message that has an obvious fix I will do it.
* If there is an error message with no clear reason then I won't blindly make changes on the off-chance that it fixes the problem.
* If somebody says "Hey _this_ is broken, _here_ is a fix" then I'll accept the fix(es) and say "thank-you".

**Comment by hudecof** [comment]
the problem is with the  data file loading, in JS console I see

```
Failed to load resource: Preflight response is not successful
XMLHttpRequest cannot load file:///Users/hudecof/devel/github/bookmarks.public/bookmarks.data. Preflight response is not successful
```

**Comment by hudecof** [comment]
seems that CHROME has the same problem, Works only in FF

**Comment by hudecof** [comment]
```
jquery-3.1.1.min.js:4 Failed to load file:///Users/hudecof/devel/github/bookmarks.public/bookmarks.data: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
send @ jquery-3.1.1.min.js:4
```

**Comment by skx** [comment]
Yup just confirmed:

> Firefox allows the request because it accepts requests to the local file system (ie. the `file://` protocol) if they originate from there too. However Chrome denies all XMLHttpRequests to `file://` URLS.

Seems like there's no great solution here, short of suggesting that you run a local HTTP-server and open `http://localhost:XXXX`, or similar.

I use firefox so this works for me.  It's probably worth a note in the README file.

**Comment by hudecof** [comment]
OK, closing the ISSUE. This bookmarks project fullfill all my requirements except one, run in all browsers ;(
I'm not very keen on run permanently web server ;(
